# Generated by Django 2.2.1 on 2019-06-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'NA')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('aadhar_no', models.IntegerField()),
                ('bank_account_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('account_number', models.IntegerField()),
            ],
        ),
    ]
