# Generated by Django 2.2.1 on 2019-06-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeelib', '0002_auto_20190612_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employeet',
        ),
    ]
